# Generated by Django 3.0.7 on 2021-03-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kube',
            options={'ordering': ['date'], 'verbose_name': 'Kube'},
        ),
    ]
