# Generated by Django 3.0.7 on 2021-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_auto_20210309_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kube',
            options={},
        ),
    ]
